#include "../support/DearModdingUITestSupport.h"
#include <DearModdingUI/host/Host.h>
#include <algorithm>
#include <array>
#include <filesystem>
#include <limits>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

namespace vmm_tests
{
	using namespace DearModdingUI;
	using namespace support::host;

	void run_host_api_compatibility_checks(Runner& runner)
	{
		runner.test("host API extensions preserve the published prefix", [] {
			require(
				offsetof(DMUI_HostAPI, beginSettingsRowEx) ==
						DMUI_HOST_API_END_SETTINGS_TABLE_SIZE &&
					DMUI_HOST_API_BEGIN_SETTINGS_ROW_EX_SIZE <
						DMUI_HOST_API_REGISTER_PAGE_ACTIVITY_OBSERVER_SIZE &&
					DMUI_HOST_API_REGISTER_PAGE_ACTIVITY_OBSERVER_SIZE <
						DMUI_HOST_API_DRAW_LINK_ROW_SIZE &&
					DMUI_HOST_API_DRAW_LINK_ROW_SIZE <
						DMUI_HOST_API_DRAW_FAQ_SIZE &&
					DMUI_HOST_API_DRAW_FAQ_SIZE <
						DMUI_HOST_API_REPORT_DIAGNOSTIC_SIZE &&
					DMUI_HOST_API_REPORT_DIAGNOSTIC_SIZE ==
						offsetof(DMUI_HostAPI, queryServices) &&
					DMUI_HOST_API_QUERY_SERVICES_SIZE <
						DMUI_HOST_API_SET_HOTKEY_ACTION_ENABLED_SIZE &&
					DMUI_HOST_API_SET_HOTKEY_ACTION_ENABLED_SIZE <
						DMUI_HOST_API_IMPORT_D3D11_IMAGE_SIZE &&
					DMUI_HOST_API_IMPORT_D3D11_IMAGE_SIZE <
						DMUI_HOST_API_DRAW_IMAGE_SIZE &&
					DMUI_HOST_API_DRAW_IMAGE_SIZE <
						DMUI_HOST_API_RELEASE_IMAGE_SIZE &&
					DMUI_HOST_API_RELEASE_IMAGE_SIZE <
						DMUI_HOST_API_QUERY_IMAGE_SIZE &&
					DMUI_HOST_API_QUERY_IMAGE_SIZE <
						DMUI_HOST_API_CONFIGURE_OVERLAY_SIZE &&
					DMUI_HOST_API_CONFIGURE_OVERLAY_SIZE <
						DMUI_HOST_API_QUERY_OVERLAY_SIZE &&
					DMUI_HOST_API_QUERY_OVERLAY_SIZE <
						DMUI_HOST_API_POST_NOTIFICATION_SIZE &&
					DMUI_HOST_API_POST_NOTIFICATION_SIZE <
						DMUI_HOST_API_DRAW_ANNOTATED_PLOT_SIZE &&
					DMUI_HOST_API_DRAW_ANNOTATED_PLOT_SIZE <
						DMUI_HOST_API_REQUEST_DIALOG_SIZE &&
					DMUI_HOST_API_REQUEST_DIALOG_SIZE <
						DMUI_HOST_API_POLL_DIALOG_EVENT_SIZE &&
					DMUI_HOST_API_POLL_DIALOG_EVENT_SIZE <
						DMUI_HOST_API_RESOLVE_DIALOG_SUBMISSION_SIZE &&
					DMUI_HOST_API_RESOLVE_DIALOG_SUBMISSION_SIZE <
						DMUI_HOST_API_CANCEL_DIALOG_SIZE &&
					DMUI_HOST_API_CANCEL_DIALOG_SIZE == 400 &&
					DMUI_HOST_API_CANCEL_DIALOG_SIZE <
						DMUI_HOST_API_CREATE_IMAGE_SIZE &&
					DMUI_HOST_API_CREATE_IMAGE_SIZE <
						DMUI_HOST_API_UPDATE_IMAGE_SIZE &&
					DMUI_HOST_API_UPDATE_IMAGE_SIZE <
						DMUI_HOST_API_REGISTER_CATEGORY_SIZE &&
					DMUI_HOST_API_REGISTER_CATEGORY_SIZE <
						DMUI_HOST_API_OPEN_EXTERNAL_SIZE &&
					DMUI_HOST_API_OPEN_EXTERNAL_SIZE <
						DMUI_HOST_API_QUERY_UI_API_SIZE &&
					sizeof(DMUI_HostAPI) ==
						DMUI_HOST_API_QUERY_UI_API_SIZE,
				"the versioned host API prefix moved");
		});

	}
}
